### ISSUE TITLE
Example project brings up blank screen

### ISSUE THREAD

**Issue by Christlofer** [PrashantMangukiya/SwiftColorPicker#2]
Hi there

I have been trying to implement this code all day, but it crashes the app every time, and returns an error:

specialized_fatalErrorMessage(StaticString, StaticString, StaticString, UInt) -> ()

I have no idea what this means!

I loaded this project so that I could take a look at a working version to try and work our where I am going wrong, but actually this version does nothing! After the loading screen it is just a plain white page!

Please can somebody help me to see where I am going wrong? I can post some code up if that helps but there are a few pages of it plus the Colors plist... 

Any help would be greatly appreciated, please understand that I am very new to this.

Thanks

Chris

**Comment by PrashantMangukiya** [comment]
Hello Christlofer,

I just tested this code using Xcode 7.3 , it is working fine as expected. Can you please give more idea about the error you are encountering for the same code. Did you tried the same code downloaded from my Git or used within other project. Kindly give more information so I can correct my code if it generates error  at certain way.

Regards,
- Prashant

**Comment by Christlofer** [comment]
Hi Prashant,

Thanks for your reply.

Look this is probably me being dumb, but I have been trying really hard to
get this to work within my app. I was trying to implement it over a second
view controller, and followed your instructions very closely.

Having failed at this multiple times I downloaded your project
“SwiftColorPicker” and tried running that, but it just brings up a blank
screen. When I try to change the device in the simulator it tells me this:

“ The run destination iPhone 6 Plus is not valid for Running the scheme
'SwiftColorPicker’. “

I don’t know whether or not this is part of my issue, but I am so new to
this I am really struggling to see what I have done wrong!

I expect your code is excellent, and it is just me who is having the isues!

Thanks for your help

Chris D

**Comment by PrashantMangukiya** [comment]
Hello Chris,
It was due to Xcode 7.3 change default device setting. Please make sure to set Devices as "Universal", It will works fine. I have attached screen shot that shows red indicator where you have to set devices. I hope this will solve your blank screen problem. Please message me once you get the project working so I can close the issue.

Prashant

![device-settings](https://cloud.githubusercontent.com/assets/7823358/14411709/97310c86-ff6d-11e5-85b7-222ec4a15728.jpg)

**Comment by Christlofer** [comment]
Ah ok, great, that works fine thank you!

Not sure why I can’t get it to work in the context of my app but i will
keep on trying now that I know it should work fine!

**Comment by PrashantMangukiya** [comment]
ok thank you for the message.

**Comment by Christlofer** [comment]
Hi again

Thanks for your help once again. Just for your info I worked out that I had
not  put the Colors.plist in the root folder - this seemed to sort out the
issue
